Job description file for hard filtering
Mae Goldgraben, 26May2018

TEMPLATE v1

=========== Data location and analysis settings =============

Data server: admin@mgqnap2.medschl.cam.ac.uk
Project location: /share/mae/

project: IHCAP75_atm_aml/germline_analysis_all_timepts
dataset: ihcap_75_Aug17_vqsr
filter name: D0Q100_std

Min DP: 0.0
Min QUAL: 100.0

Notes: 
- DP refers to total depth over all samples (e.g. use num of samples * 10)
- QUAL threshold may be selected on the basis of Ti/Tv ratio in vcfstats
- Keep at least one digit after decimal point in the thresholds  

======================= HPC settings ========================

working_folder: /rds/project/erf33/rds-erf33-medgen/users/mae

Account to use on HPC: TISCHKOWITZ-SL2-CPU
Max time to request (hrs.min.sec): 01.00.00

==================== Pipeline summary ======================

#Filtering vcf by QUAL and DP

===================== Standard settings =====================
#Use script "p06A_wes_hard_filter" to retain variants that fail hard filters

scripts_folder: /rds/project/erf33/rds-erf33-medgen/scripts/wes_pipeline_01.18/p06_wes_hard_filter
start_script: a00_start_pipeline.sh

Tools
-----

tools_folder: /rds/project/erf33/rds-erf33-medgen/tools
java: java/jre1.8.0_40/bin/java
gatk: gatk/gatk-3.6-0/GenomeAnalysisTK.jar

bcftools: bcftools/bcftools-1.2/bin/bcftools
plot_vcfstats: bcftools/bcftools-1.2/bin/plot-vcfstats

Updated version of Python matplotlib library for plot-vcfstats script
python_bin: python/python_2.7.10/bin/

r_folder: r/R-3.2.0/bin

r_bin_folder: r/R-3.2.2/bin/
r_lib_folder: r/R-3.2.2/lib64/R/library

Note about using different R versions
-------------------------------------
R-3.2.0 is used here for plotting in GATK-VQSR, 
which requires a specific set of R-libraries.
For being accessable by GATK, R-3.2.0 is added to PATH.
  
R-3.2.2 is used here to genereate html and pdf reports with rmarkdown.
Generating reports with Rmarkdown is pernickety about environment. 
It requires recent versions of several system libraries
and a number of additional R libraries to be pre-installed.
The external libraries are loaded as modules in *.sb.sh script:
module load gcc/5.2.0
module load boost/1.50.0
module load texlive/2015
module load pandoc/1.15.2.1
Rmarkdown library has to be installed in the r_lib_folder
shown above. 

Historically, at the time of the scripts preparation, it happened
that different sets of libraries were available in different versions
of R installed in the toolbox. This resulted to the temporary configuration
of using two different R versions at the same time. Then, there was 
no time and need to change it.  

See details details about required R-libraries in the 
r-installation notes in the tools folder.

Resources
---------

resources_folder: /rds/project/erf33/rds-erf33-medgen/resources

decompressed_bundle_folder: gatk_bundle/b37/decompressed
ref_genome: human_g1k_v37.fasta

targets_folder: illumina_nextera
targets_intervals: nexterarapidcapture_exome_targetedregions_v1.2.b37.intervals

targets_bed: nexterarapidcapture_exome_targetedregions_v1.2.b37.bed
targets_bed is not used by current pipeline; However it could be used later to target vcf-stats

Working sub-folders
-------------------

logs_folder: logs
histograms_folder: histograms
vcfstats_folder: vcfstats
